[package]
name = "validate-npm-package-name"
version = "0.1.0"
authors = ["Chris Krycho <hello@chriskrycho.com>"]
edition = "2018"

[lib]

[dependencies]
lazy_static = "1.3.0"
percent-encoding = "1.0.1"
regex = "1.5.4"
